#!/usr/bin/env tsx
import * as fs from "fs"
import * as path from "path"

function findTsxFiles(dir: string) {
  const files: string[] = []
  const entries = fs.readdirSync(dir, { withFileTypes: true })

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...findTsxFiles(fullPath))
    } else if (entry.isFile() && entry.name.endsWith(".tsx")) {
      files.push(fullPath)
    }
  }

  return files
}

function scanLucideIconUsage() {
  const lucideIcons = new Set<string>()

  const registryBasesDir = path.join(process.cwd(), "registry/bases")
  const files = findTsxFiles(registryBasesDir)
  
  // Match IconPlaceholder with lucide attribute
  const iconPlaceholderRegex = /<IconPlaceholder\s+([^>]*?)lucide=["']([^"']+)["']([^>]*?)\/?>/g

  for (const file of files) {
    const content = fs.readFileSync(file, "utf-8")

    let match
    while ((match = iconPlaceholderRegex.exec(content)) !== null) {
      const iconName = match[2]
      lucideIcons.add(iconName)
    }
  }

  return lucideIcons
}

function generateLucideIconFile(icons: Set<string>) {
  const outputDir = path.join(process.cwd(), "registry/icons")
  const sortedIcons = Array.from(icons).sort()

  if (sortedIcons.length === 0) {
    console.log("⚠ No Lucide icons found in registry")
    return
  }

  const content = `// Auto-generated by scripts/build-icons.ts
// This file exports only the Lucide icons used in the component registry
${sortedIcons.map((icon) => `export { ${icon} } from "lucide-react"`).join("\n")}
`

  const filename = "__lucide__.ts"
  fs.writeFileSync(path.join(outputDir, filename), content)

  console.log(`✓ Generated Lucide icon file: ${sortedIcons.length} icons`)
}

function main() {
  const lucideIcons = scanLucideIconUsage()
  generateLucideIconFile(lucideIcons)
}

const isWatchMode = process.argv.includes("--watch")

if (isWatchMode) {
  const REGISTRY_DIR = path.join(process.cwd(), "registry/bases")

  async function startWatcher() {
    const { default: chokidar } = await import("chokidar")

    main()

    const watcher = chokidar.watch(REGISTRY_DIR, {
      ignored: /(^|[/\\])\../,
      persistent: true,
      ignoreInitial: true,
    })

    const rebuild = (filename: string) => {
      if (!filename.endsWith(".tsx")) return

      try {
        main()
      } catch (error) {
        console.error("❌ Icons build failed:", error)
      }
    }

    watcher.on("error", (error) => {
      console.error("❌ Watcher error:", error)
    })

    watcher.on("change", rebuild)
    watcher.on("add", rebuild)

    process.on("SIGINT", async () => {
      await watcher.close()
      process.exit(0)
    })
  }

  startWatcher()
} else {
  main()
}
